FROM python:3.10.13

WORKDIR /build
COPY ./requirements.txt .
COPY ./apps/flower-predictor/app-requirements.txt .
COPY ./libs ./libs
RUN pip3 install ./libs
RUN pip3 install -r requirements.txt
RUN pip3 install -r app-requirements.txt

RUN rm -fR /build

WORKDIR /work
COPY ./apps/flower-predictor/app .
COPY ./_models/model_iris_final.h5 .

EXPOSE 8080
CMD uvicorn --workers=2 --host 0.0.0.0 --port 8080 app:app

