apiVersion: v1
kind: Service
metadata:
  name: flower-predictor
spec:
  type: NodePort
  selector:
    app: flowerclassiferApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080