#FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0.1-cpu-py310-ubuntu20.04-ec2
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.0.1-gpu-py310-cu121-ubuntu20.04-ec2
#RUN pip install tensorboardX==2.4 pyarrow==13.0.0 torch==2.0.1 torchvision==0.15.2 tqdm==4.66.1 ray[tune]==2.7.0 mlflow==2.7.0

ENTRYPOINT ["/bin/bash"]