FROM python:3.11.5

WORKDIR /build
COPY ./requirements.txt .
COPY ./apps/{{ cookiecutter.app_name }}/app-requirements.txt .
COPY ./libs ./libs
RUN pip3 install ./libs
RUN pip3 install -r requirements.txt
RUN pip3 install -r app-requirements.txt

RUN rm -fR /build

WORKDIR /work

